Fix invalid logical constant creation in sdm845.
This code incorrectly uses || to combine a bunch of state constants. The
next Clang warns on this buggy pattern.

hardware/qcom/sdm845/media/mm-video-v4l2/vidc/venc/src/omx_video_base.cpp:1097:40: error: use of logical '||' with constant operand [-Werror,-Wconstant-logical-operand]
        if (eState == (OMX_StateLoaded || OMX_StateWaitForResources
                                       ^  ~~~~~~~~~~~~~~~~~~~~~~~~~
hardware/qcom/sdm845/media/mm-video-v4l2/vidc/venc/src/omx_video_base.cpp:1097:40: note: use '|' for a bitwise operation
        if (eState == (OMX_StateLoaded || OMX_StateWaitForResources
                                       ^~
                                       |

Bug: http://b/110779387
Test: Build with new toolchain.
Change-Id: If791d503a43740f83189f181964931a26cb77fe2
Merged-In: If791d503a43740f83189f181964931a26cb77fe2
(cherry picked from commit 891f019d60607816fc482c09cbd360f6d60f89fc)